# Copyright 2022-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.config.upf.sriov.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-device-plugin
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-sriov-device-plugin-amd64
  labels:
    tier: node
    app: sriovdp
spec:
  selector:
    matchLabels:
      name: sriov-device-plugin
  template:
    metadata:
      labels:
        name: sriov-device-plugin
        tier: node
        app: sriovdp
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      initContainers:
        - name: init-sriov-plugin
          image: docker.io/omecproject/omec-cni:1.1.7
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - cp /tmp/cni/bin/{sriov,vfioveth,jq,static,dhcp} /host/opt/cni/bin/;
              chmod +x /host/opt/cni/bin/vfioveth
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
      serviceAccountName: sriov-device-plugin
      containers:
        - name: kube-sriovdp
          image: docker.io/nfvpe/sriov-device-plugin:v3.3.2
          imagePullPolicy: IfNotPresent
          args:
            - --log-dir=sriovdp
            - --log-level=10
          securityContext:
            privileged: true
          volumeMounts:
            - name: devicesock
              mountPath: /var/lib/kubelet/
              readOnly: false
            - name: log
              mountPath: /var/log
            - name: config-volume
              mountPath: /etc/pcidp
            - name: device-info
              mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: log
          hostPath:
            path: /var/log
        - name: device-info
          hostPath:
            path: /var/run/k8s.cni.cncf.io/devinfo/dp
            type: DirectoryOrCreate
        - name: config-volume
          configMap:
            name: sriovdp-config
            items:
              - key: config.json
                path: config.json
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
{{- end }}
