---
# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: Mobile Sim Provisioning services
name: omec-sub-provision
icon: https://guide.opencord.org/logos/cord.svg

version: 1.0.1
