---
# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2020-present Open Networking Foundation

#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: SD-Core 5G control plane services
name: 5g-control-plane
icon: https://guide.opencord.org/logos/cord.svg

version: 0.9.2

dependencies:
  - name: mongodb
    version: 13.6.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.deploy
  - name: kafka
    version: 20.0.4
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.deploy

