---
# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2020-present Open Networking Foundation

#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
description: SD-Core 5G control plane services
name: 5g-control-plane
icon: https://guide.opencord.org/logos/cord.svg

version: 3.1.0

dependencies:
  - name: mongodb
    version: 16.5.45
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.deploy
  - name: kafka
    version: 32.4.3
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.deploy

