---
# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: sd-core
description: SD-Core control plane services
icon: https://guide.opencord.org/logos/cord.svg
type: application
version: 0.11.6
home: https://opennetworking.org/sd-core/
maintainers:
  - name: SD-Core Support
    email: support@opennetworking.org

dependencies:
  - name: omec-control-plane
    version: 0.11.0
    repository: https://charts.aetherproject.org
    condition: omec-control-plane.enable4G

  - name: omec-sub-provision
    version: 0.5.1
    repository: https://charts.aetherproject.org
    condition: omec-sub-provision.enable

  - name: 5g-control-plane
    version: 0.7.4
    repository: https://charts.aetherproject.org
    condition: 5g-control-plane.enable5G

  - name: bess-upf
    version: 0.0.6
    repository: https://charts.aetherproject.org
    alias: omec-user-plane
    condition: omec-user-plane.enable

  - name: 5g-ran-sim
    version: 0.5.3
    repository: https://charts.aetherproject.org
    condition: 5g-ran-sim.enable
