---
# Copyright 2020-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0
#


apiVersion: v2
name: sd-core
description: SD-Core control plane services
icon: https://guide.opencord.org/logos/cord.svg
type: application
version: 2.2.8
home: https://opennetworking.org/sd-core/
maintainers:
  - name: SD-Core Support
    email: dev@lists.aetherproject.org

dependencies:
  - name: omec-control-plane
    version: 0.13.0
    repository: "file://../omec-control-plane"
    condition: omec-control-plane.enable4G

  - name: omec-sub-provision
    version: 2.0.2
    repository: "file://../omec-sub-provision"
    condition: omec-sub-provision.enable

  - name: 5g-control-plane
    version: 2.2.8
    repository: "file://../5g-control-plane"
    condition: 5g-control-plane.enable5G

  - name: bess-upf
    version: 1.3.1
    repository: "file://../bess-upf"
    alias: omec-user-plane
    condition: omec-user-plane.enable

  - name: 5g-ran-sim
    version: 2.0.2
    repository: "file://../5g-ran-sim"
    condition: 5g-ran-sim.enable
