{{/*
# Copyright 2024 Intel Corporation

# SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ausf-certs
  labels:
{{ tuple "ausf" . | include "5g-control-plane.metadata_labels" | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
{{- with .Values.config.ausf.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{ ( include "5g-control-plane.gen-certs" . ) | indent 2 }}
